<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ru.mihail.labs</groupId>
    <artifactId>java-backend-labs</artifactId>
    <!--  Правила версионирования: https://semver.org/lang/ru/  -->
    <!--  Словом SNAPSHOT помечается нестабильная версия, код которой может меняться  -->
    <version>1.0.0-SNAPSHOT</version>

    <!--  Это корневой pom, поэтому при сборке не нужно паковать jar - указываем "pom"  -->
    <packaging>pom</packaging>

    <!--  Задаем все версии внутри properties  -->
    <properties>
        <maven.compiler.release>25</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <maven.compiler.plugin.version>3.15.0</maven.compiler.plugin.version>
        <maven-surefire-plugin.version>3.5.5</maven-surefire-plugin.version>
        <maven.shade.plugin.version>3.6.2</maven.shade.plugin.version>
        <maven.build.helper.plugin.version>3.6.1</maven.build.helper.plugin.version>
        <openapi.maven.plugin.version>7.22.0</openapi.maven.plugin.version>

        <junit.version>6.1.0</junit.version>
        <jackson.version>3.1.3</jackson.version>
        <lombok.version>1.18.46</lombok.version>
        <mapstruct.version>1.6.3</mapstruct.version>
        <lombok.mapstruct.binding.version>0.2.0</lombok.mapstruct.binding.version>
        <jooby.version>4.5.1</jooby.version>
        <javalin.version>7.2.2</javalin.version>
        <flyway.version>12.8.1</flyway.version>
        <grpc.version>1.81.0</grpc.version>
        <jdbi.version>3.53.0</jdbi.version>
        <jacoco.version>0.8.14</jacoco.version>
        <testcontainers.version>2.0.5</testcontainers.version>
        <shedlock.version>7.7.0</shedlock.version>
        <s3.version>2.44.12</s3.version>
        <redisson.version>4.4.0</redisson.version>
        <temporal.version>1.29.0</temporal.version>
        <captcha.version>1.6.2</captcha.version>
        <wiremock.version>3.13.2</wiremock.version>

        <spring.dependencies.version>4.1.1</spring.dependencies.version>
        <spring.openapi.version>3.0.3</spring.openapi.version>
    </properties>

    <modules>
        <module>lab-1</module>
    </modules>

    <!--  Перечисляем все внешние зависимости с указанием версий из properties  -->
    <!--  Таким образом, во всех модулях будут единые версии зависимостей       -->
    <dependencyManagement>
        <dependencies>
            <!--  JUnit (Jupiter) для тестирования  -->
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter</artifactId>
                <version>${junit.version}</version>
                <scope>test</scope>
            </dependency>
            <!--  jackson для работы с json  -->
            <dependency>
                <groupId>tools.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <!--  lombok для генерации однотипного кода  -->
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
                <scope>compile</scope>
            </dependency>
            <!--  mapstruct для генерации мапперов  -->
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct.version}</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>${mapstruct.version}</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok-mapstruct-binding</artifactId>
                <version>${lombok.mapstruct.binding.version}</version>
                <scope>compile</scope>
            </dependency>
            <!-- библиотека легкого создания web-сервера -->
            <dependency>
                <groupId>io.jooby</groupId>
                <artifactId>jooby</artifactId>
                <version>${jooby.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jooby</groupId>
                <artifactId>jooby-netty</artifactId>
                <version>${jooby.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jooby</groupId>
                <artifactId>jooby-test</artifactId>
                <version>${jooby.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>io.jooby</groupId>
                <artifactId>jooby-jackson</artifactId>
                <version>${jooby.version}</version>
            </dependency>
            <dependency>
                <groupId>io.javalin</groupId>
                <artifactId>javalin</artifactId>
                <version>${javalin.version}</version>
            </dependency>
            <dependency>
                <groupId>org.flywaydb</groupId>
                <artifactId>flyway-core</artifactId>
                <version>${flyway.version}</version>
            </dependency>
            <dependency>
                <groupId>org.flywaydb</groupId>
                <artifactId>flyway-database-postgresql</artifactId>
                <version>${flyway.version}</version>
            </dependency>
            <!-- ORM -->
            <dependency>
                <groupId>org.jdbi</groupId>
                <artifactId>jdbi3-core</artifactId>
                <version>${jdbi.version}</version>
            </dependency>
            <dependency>
                <groupId>org.jdbi</groupId>
                <artifactId>jdbi3-sqlobject</artifactId>
                <version>${jdbi.version}</version>
            </dependency>
            <!-- testcontainers -->
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers</artifactId>
                <version>${testcontainers.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers-junit-jupiter</artifactId>
                <version>${testcontainers.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers-postgresql</artifactId>
                <version>${testcontainers.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers-kafka</artifactId>
                <version>${testcontainers.version}</version>
                <scope>test</scope>
            </dependency>
            <!-- для scheduler задач -->
            <dependency>
                <groupId>net.javacrumbs.shedlock</groupId>
                <artifactId>shedlock-spring</artifactId>
                <version>${shedlock.version}</version>
            </dependency>
            <dependency>
                <groupId>net.javacrumbs.shedlock</groupId>
                <artifactId>shedlock-provider-jdbc-template</artifactId>
                <version>${shedlock.version}</version>
            </dependency>
            <!-- s3 client -->
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>s3</artifactId>
                <version>${s3.version}</version>
            </dependency>
            <!-- redis client -->
            <dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson</artifactId>
                <version>${redisson.version}</version>
            </dependency>
            <!-- temporal worker -->
            <dependency>
                <groupId>io.temporal</groupId>
                <artifactId>temporal-spring-boot-starter</artifactId>
                <version>${temporal.version}</version>
            </dependency>
            <!-- captcha generator -->
            <dependency>
                <groupId>com.github.whvcse</groupId>
                <artifactId>easy-captcha</artifactId>
                <version>${captcha.version}</version>
            </dependency>
            <!-- wiremock -->
            <dependency>
                <groupId>org.wiremock</groupId>
                <artifactId>wiremock-standalone</artifactId>
                <version>${wiremock.version}</version>
                <scope>test</scope>
            </dependency>

            <!--  все версии зависимостей spring в одном пакете -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.dependencies.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-bom</artifactId>
                <version>${spring.openapi.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <!-- Настройка плагинов для сборки проекта -->
    <build>
        <pluginManagement>
            <plugins>
                <!-- Плагин с дополнительными параметрами сборки (например настройка Lombok) -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven.compiler.plugin.version}</version>
                </plugin>
                <!-- Плагин для запуска тестов -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${maven-surefire-plugin.version}</version>
                </plugin>
                <!-- Плагин для создания fat jar -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-shade-plugin</artifactId>
                    <version>${maven.shade.plugin.version}</version>
                    <configuration>
                        <createDependencyReducedPom>false</createDependencyReducedPom>
                    </configuration>
                </plugin>
                <!-- Дополнительные параметры сложной сборки -->
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>build-helper-maven-plugin</artifactId>
                    <version>${maven.build.helper.plugin.version}</version>
                </plugin>
                <!-- Плагин для кодогенерации по open api -->
                <plugin>
                    <groupId>org.openapitools</groupId>
                    <artifactId>openapi-generator-maven-plugin</artifactId>
                    <version>${openapi.maven.plugin.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

</project>
